// <auto-generated />
using System;
using Coinnova.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coinnova.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coinnova.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("category_pkey");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdUser1")
                        .HasColumnType("integer")
                        .HasColumnName("id_user1");

                    b.Property<int>("IdUser2")
                        .HasColumnType("integer")
                        .HasColumnName("id_user2");

                    b.HasKey("Id")
                        .HasName("chat_pkey");

                    b.HasIndex("IdUser1");

                    b.HasIndex("IdUser2");

                    b.ToTable("chat", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdParentComment")
                        .HasColumnType("integer")
                        .HasColumnName("id_parent_comment");

                    b.Property<int>("IdPost")
                        .HasColumnType("integer")
                        .HasColumnName("id_post");

                    b.Property<int?>("IdType")
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int?>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("likes");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("comment_pkey");

                    b.HasIndex("IdParentComment");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUser");

                    b.HasIndex(new[] { "IdType" }, "idx_comment_type");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.CommentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("comment_type_pkey");

                    b.ToTable("comment_type", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdInstitution")
                        .HasColumnType("integer")
                        .HasColumnName("id_institution");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("community_pkey");

                    b.HasIndex("IdInstitution");

                    b.ToTable("community", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.CommunityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int?>("IdCommunity")
                        .HasColumnType("integer")
                        .HasColumnName("id_community");

                    b.HasKey("Id")
                        .HasName("community_category_pkey");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdCommunity");

                    b.ToTable("community_category", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.CommunityMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommunity")
                        .HasColumnType("integer")
                        .HasColumnName("id_community");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<DateTime?>("Joinedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joinedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("community_member_pkey");

                    b.HasIndex("IdCommunity");

                    b.HasIndex("IdUser");

                    b.ToTable("community_member", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Createdby")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("enddate");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<DateTime>("Initialdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("initialdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Place")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("place");

                    b.Property<string>("Rulesurl")
                        .HasColumnType("text")
                        .HasColumnName("rulesurl");

                    b.Property<bool>("VisibilityPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("visibility_private");

                    b.HasKey("Id")
                        .HasName("event_pkey");

                    b.HasIndex("Createdby");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.EventCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int?>("IdEvent")
                        .HasColumnType("integer")
                        .HasColumnName("id_event");

                    b.HasKey("Id")
                        .HasName("event_category_pkey");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdEvent");

                    b.ToTable("event_category", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("institution_pkey");

                    b.ToTable("institution", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.InstitutionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdEvent")
                        .HasColumnType("integer")
                        .HasColumnName("id_event");

                    b.Property<int?>("IdInstitution")
                        .HasColumnType("integer")
                        .HasColumnName("id_institution");

                    b.HasKey("Id")
                        .HasName("institution_event_pkey");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdInstitution");

                    b.ToTable("institution_event", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdChat")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int>("IdSender")
                        .HasColumnType("integer")
                        .HasColumnName("id_sender");

                    b.HasKey("Id")
                        .HasName("message_pkey");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdSender");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("RefId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_id");

                    b.HasKey("Id")
                        .HasName("notification_pkey");

                    b.HasIndex("IdUser");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCommunity")
                        .HasColumnType("integer")
                        .HasColumnName("id_community");

                    b.Property<int>("IdType")
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<int?>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("likes");

                    b.Property<string>("Textcontent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("textcontent");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("post_pkey");

                    b.HasIndex("IdCommunity");

                    b.HasIndex("IdUser");

                    b.HasIndex(new[] { "IdType" }, "idx_post_type");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.PostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("post_type_pkey");

                    b.ToTable("post_type", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("role_pkey");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int?>("IdInstitution")
                        .HasColumnType("integer")
                        .HasColumnName("id_institution");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("User_pkey");

                    b.HasIndex("IdInstitution");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Email" }, "User_email_key")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Chat", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.User", "IdUser1Navigation")
                        .WithMany("ChatIdUser1Navigation")
                        .HasForeignKey("IdUser1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_id_user1_fkey");

                    b.HasOne("Coinnova.Domain.Entities.User", "IdUser2Navigation")
                        .WithMany("ChatIdUser2Navigation")
                        .HasForeignKey("IdUser2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_id_user2_fkey");

                    b.Navigation("IdUser1Navigation");

                    b.Navigation("IdUser2Navigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Comment", "IdParentCommentNavigation")
                        .WithMany("InverseIdParentCommentNavigation")
                        .HasForeignKey("IdParentComment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comment_id_parent_comment_fkey");

                    b.HasOne("Coinnova.Domain.Entities.Post", "IdPostNavigation")
                        .WithMany("Comment")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("comment_id_post_fkey");

                    b.HasOne("Coinnova.Domain.Entities.CommentType", "IdTypeNavigation")
                        .WithMany("Comment")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("comment_id_type_fkey");

                    b.HasOne("Coinnova.Domain.Entities.User", "IdUserNavigation")
                        .WithMany("Comment")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("comment_id_user_fkey");

                    b.Navigation("IdParentCommentNavigation");

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdTypeNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Community", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Institution", "IdInstitutionNavigation")
                        .WithMany("Community")
                        .HasForeignKey("IdInstitution")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("community_id_institution_fkey");

                    b.Navigation("IdInstitutionNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.CommunityCategory", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Category", "IdCategoryNavigation")
                        .WithMany("CommunityCategory")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("community_category_id_category_fkey");

                    b.HasOne("Coinnova.Domain.Entities.Community", "IdCommunityNavigation")
                        .WithMany("CommunityCategory")
                        .HasForeignKey("IdCommunity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("community_category_id_community_fkey");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdCommunityNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.CommunityMember", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Community", "IdCommunityNavigation")
                        .WithMany("CommunityMember")
                        .HasForeignKey("IdCommunity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_member_id_community_fkey");

                    b.HasOne("Coinnova.Domain.Entities.User", "IdUserNavigation")
                        .WithMany("CommunityMember")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_member_id_user_fkey");

                    b.Navigation("IdCommunityNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Event", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.User", "CreatedbyNavigation")
                        .WithMany("Event")
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("event_createdby_fkey");

                    b.Navigation("CreatedbyNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.EventCategory", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Category", "IdCategoryNavigation")
                        .WithMany("EventCategory")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("event_category_id_category_fkey");

                    b.HasOne("Coinnova.Domain.Entities.Event", "IdEventNavigation")
                        .WithMany("EventCategory")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("event_category_id_event_fkey");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdEventNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.InstitutionEvent", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Event", "IdEventNavigation")
                        .WithMany("InstitutionEvent")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("institution_event_id_event_fkey");

                    b.HasOne("Coinnova.Domain.Entities.Institution", "IdInstitutionNavigation")
                        .WithMany("InstitutionEvent")
                        .HasForeignKey("IdInstitution")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("institution_event_id_institution_fkey");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdInstitutionNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Message", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Chat", "IdChatNavigation")
                        .WithMany("Message")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_id_chat_fkey");

                    b.HasOne("Coinnova.Domain.Entities.User", "IdSenderNavigation")
                        .WithMany("Message")
                        .HasForeignKey("IdSender")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("message_id_sender_fkey");

                    b.Navigation("IdChatNavigation");

                    b.Navigation("IdSenderNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.User", "IdUserNavigation")
                        .WithMany("Notification")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notification_id_user_fkey");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Post", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Community", "IdCommunityNavigation")
                        .WithMany("Post")
                        .HasForeignKey("IdCommunity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("post_id_community_fkey");

                    b.HasOne("Coinnova.Domain.Entities.PostType", "IdTypeNavigation")
                        .WithMany("Post")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("post_id_type_fkey");

                    b.HasOne("Coinnova.Domain.Entities.User", "IdUserNavigation")
                        .WithMany("Post")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("post_id_user_fkey");

                    b.Navigation("IdCommunityNavigation");

                    b.Navigation("IdTypeNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.User", b =>
                {
                    b.HasOne("Coinnova.Domain.Entities.Institution", "IdInstitutionNavigation")
                        .WithMany("User")
                        .HasForeignKey("IdInstitution")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("User_id_institution_fkey");

                    b.HasOne("Coinnova.Domain.Entities.Role", "IdRoleNavigation")
                        .WithMany("User")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("User_id_role_fkey");

                    b.Navigation("IdInstitutionNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Category", b =>
                {
                    b.Navigation("CommunityCategory");

                    b.Navigation("EventCategory");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Message");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Comment", b =>
                {
                    b.Navigation("InverseIdParentCommentNavigation");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.CommentType", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Community", b =>
                {
                    b.Navigation("CommunityCategory");

                    b.Navigation("CommunityMember");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventCategory");

                    b.Navigation("InstitutionEvent");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Institution", b =>
                {
                    b.Navigation("Community");

                    b.Navigation("InstitutionEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.PostType", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Coinnova.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatIdUser1Navigation");

                    b.Navigation("ChatIdUser2Navigation");

                    b.Navigation("Comment");

                    b.Navigation("CommunityMember");

                    b.Navigation("Event");

                    b.Navigation("Message");

                    b.Navigation("Notification");

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
