<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="Mapster" Version="7.*" />
      <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.1" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Coinnova.Domain\Coinnova.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UseCases\Auth\Commands\" />
      <Folder Include="UseCases\Auth\Queries\" />
      <Folder Include="UseCases\Categories\Commands\" />
      <Folder Include="UseCases\Categories\Queries\" />
      <Folder Include="UseCases\Comments\Commands\" />
      <Folder Include="UseCases\Comments\Queries\" />
      <Folder Include="UseCases\Communities\Commands\" />
      <Folder Include="UseCases\Communities\Queries\" />
      <Folder Include="UseCases\CommunityMembers\Commands\" />
      <Folder Include="UseCases\CommunityMembers\Queries\" />
      <Folder Include="UseCases\Events\Commands\" />
      <Folder Include="UseCases\Events\Queries\" />
      <Folder Include="UseCases\Institutions\Commands\" />
      <Folder Include="UseCases\Institutions\Queries\" />
      <Folder Include="UseCases\Posts\Commands\" />
      <Folder Include="UseCases\Posts\Queries\" />
      <Folder Include="UseCases\Users\Commands\" />
      <Folder Include="UseCases\Users\Queries\" />
    </ItemGroup>

</Project>
